### ISSUE TITLE
{{< include file.qmd >}} remove table of content of suppmat qmd

### ISSUE THREAD

**Issue by clemdelrevo** [mikemahoney218/quarto-arxiv#19]
Hi !

Thank you for your template.
I try to include my qmd file as suppmat like in your preprint "MAPPING HISTORICAL FOREST BIOMASS FOR STOCK-CHANGE ASSESSMENTS AT PARCEL TO LANDSCAPE SCALES"  in my main qmd

```
# Literature cited

::: {#refs}
:::

{{< include _extended_data.qmd >}}
```

but the table of content in the suppmat is remove and numbers of pages are not renumbering from 1.

here my suppmat YAML

```
format: 
  pdf: 
    toc: true
    colorlinks: true
crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
    - kind: float
      key: supptbl
      latex-env: supptbl
      reference-prefix: Table S
      space-before-numbering: false
```

and the YAML of my main qmd

```
title: ...
author:
  - name: ...
    email: ...
    affiliation: ...
      - name: ...
        city : ...
  - name: ...
    email: ...
    affiliation :...
      - name : ...
        city : ...
format:
  docx: default
  pdf: default
  arxiv-pdf:
    keep-tex: false  
    toc: true
bibliography: references.bib
csl: meps_model.csl
linenumbers: true
authorcols: true
editor: 
  markdown: 
    wrap: sentence
crossref:
  custom:
    - kind: float
      key: suppfig
      latex-env: suppfig
      reference-prefix: Figure S
      space-before-numbering: false
      latex-list-of-description: Supplementary Figure
    - kind: float
      key: supptbl
      latex-env: supptbl
      reference-prefix: Table S
      space-before-numbering: false
      latex-list-of-description: Supplementary Table
```

I will be very grateful if you can share how to do.

Thank you
