### ISSUE TITLE
Maybe it's a feature but it looks a bit odd to me

### ISSUE THREAD

**Issue by DoktorMike** [mikemahoney218/quarto-arxiv#2]
Thanks for this awesome Arxiv template! I have a small question: When I render the pdf the author list has the first author name in bold and the others not. The first author is also one level higher than the others. Is this intentional?

**Comment by mikemahoney218** [comment]
Thanks for the report @DoktorMike ! Fixed the bolding (all authors are now bolded) in 65f2b43.

What version of quarto are you using (`quarto --version` on the command line, `quarto::quarto_version()` with the R package)? I've noticed that the way authors are arranged changes from version to version -- using v1.1.189 (today's latest version), I now see that for between 1 and 6 authors, it looks like everyone gets arranged in a vertical column. I'm not sure if I'm not understanding your second point or if the current version of Quarto fixed it for me!

**Comment by DoktorMike** [comment]
Thanks for the reply!

I have quarto version: 1.1.189

It looks like this for me

```bash
Author1
                   Author2         Author3
```

**Comment by DoktorMike** [comment]
Like this: 

![20220908_16h06m13s_grim](https://user-images.githubusercontent.com/4715779/189143650-506238be-a72b-4c4f-a626-9cc1971146e5.png)

**Comment by mikemahoney218** [comment]
Actually, this was a faster fix than anticipated:

```yaml
---
title: "Demo arXiv template"
format:
  arxiv-pdf:
    keep-tex: true  
  arxiv-html: default
author:
  - name: Michael J Mahoney
    affiliations:
      - name: Department of AI Research
        department: Desupervised ApS
        address: 1 Forestry Drive
        city: Copehagen
        country: USA
        postal-code: 2100
    orcid: 0000-0003-2402-304X
    email: fake_email@fakeyfake.com
  - name: Someone Else
    affiliations:
      - name: Department of AI Research
        department: Desupervised ApS
        address: 1 Forestry Drive
        city: Copehagen
        country: USA
        postal-code: 2100
    email: test@test.com
    orcid: 0000-0003-2402-304X
  - name: Third Person
    affiliations:
      - name: Department of AI Research
        department: Desupervised ApS
        address: 1 Forestry Drive
        city: Copehagen
        country: USA
        postal-code: 2100
    email: test@test.com
    orcid: 0000-0003-2402-304X
abstract: |
  This document is only a demo explaining how to use the template.
keywords: 
  - template
  - demo
bibliography: bibliography.bib  
---
```
![Screenshot from 2022-09-08 11-37-42](https://user-images.githubusercontent.com/38229299/189165027-0a9149e1-9c3e-4ea5-9794-e2b604645b5f.png)

In case it's of interest, the fix was changing the separator used in `title.tex`:
https://github.com/mikemahoney218/quarto-arxiv/commit/aa48d070ef58ac68287a21c5d94ac9d66499cfb0#diff-62186b5ad62a639ebe25f7422460e33ebd783a033f278120d5504cdd31c80e1aR20

Thanks for the report! I'll cut this as version 0.1.5 in a minute.
